name: Windows ISO
on: workflow_dispatch
jobs:
  build:
    name: Windows ISO [${{matrix.ztype}}]
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        ztype: [ 'xz', 'gzip', 'zip' ]

        include:
          - ztype: xz
            zext: xz
          - ztype: gzip
            zext: gz
          - ztype: zip
            zext: zip

    steps:
      - name: Configure runner
        run: |
          choco install 7zip

      - name: Download ISO file
        shell: pwsh
        run: |
          $WindowsIsoFile = "https://software-download.microsoft.com/download/sg/20348.169.210806-2348.fe_release_svc_refresh_SERVER_EVAL_x64FRE_en-us.iso"
          Invoke-WebRequest $WindowsIsoFile -OutFile "windows.iso"
          Get-FileHash "*.iso"

      - name: Compress ISO file
        shell: pwsh
        run: |
          & "7z" "a" "-t${{matrix.ztype}}" "windows.iso.${{matrix.zext}}" "windows.iso"

      - name: Compression summary
        shell: pwsh
        run: |
          Get-ChildItem | Select-Object -Property Name,Length
