name: Windows VHD
on: workflow_dispatch
jobs:
  build:
    name: Windows VHD [${{matrix.ztype}}]
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        ztype: [ 'xz', 'gzip', 'zip' ]

        include:
          - ztype: xz
            zext: xz
          - ztype: gzip
            zext: gz
          - ztype: zip
            zext: zip

    steps:
      - name: Configure runner
        run: |
          choco install 7zip
          $VSINSTALLDIR = $(vswhere.exe -latest -property installationPath)
          Remove-Item $VSINSTALLDIR -Recurse -Force

      - name: Download VHD file
        shell: pwsh
        run: |
          $WindowsVhdFile = "https://software-download.microsoft.com/download/pr/20348.169.amd64fre.fe_release_svc_refresh.210806-2348_server_serverdatacentereval_en-us.vhd"
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest $WindowsVhdFile -OutFile "windows.vhd"

      - name: Compress VHD file
        shell: pwsh
        run: |
          & "7z" "a" "-t${{matrix.ztype}}" "windows.vhd.${{matrix.zext}}" "windows.vhd"

      - name: Compression summary
        shell: pwsh
        run: |
          Get-ChildItem | Select-Object -Property Name,Length
